name: ServerSystem
version: 0.0.3#Dev
main: me.meinmex.serversystem.serversystem.ServerSystem
api-version: 1.19
authors: [ MeinMex ]
description: Server System Plugin
website: Soon
commands:
  Help:
    aliases: [ h, help ]
    usage: /help
  Fly:
    aliases: [ f, fly ]
    usage: /fly
  ClearChat:
    aliases: [ c, cc ]
    usage: /clearchat