name: ServerSystem
version: '${project.version}'
main: me.meinmex.serversystem.serversystem.ServerSystem
api-version: 1.19
authors: [ MeinMex ]
description: Server System Plugin
website: Soon
commands:
  Help:
    aliases: [ h, help ]
    usage: /help